runtime: python39
instance_class: F1

env_variables:
  FLASK_SECRET_KEY: "seu-secret-key-aqui"
  GEMINI_API_KEY: "sua-chave-gemini"
  OPENAI_API_KEY: "sua-chave-openai"
  ANTHROPIC_API_KEY: "sua-chave-anthropic"

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto 